# Generated by Django 5.1.1 on 2024-09-21 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authormodel',
            options={'verbose_name': 'Author', 'verbose_name_plural': 'Authors'},
        ),
        migrations.RemoveField(
            model_name='authormodel',
            name='name',
        ),
    ]
