# Generated by Django 5.1.1 on 2024-09-21 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmodel',
            options={'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
    ]
